<?php
use Illuminate\Database\Seeder;
use App\Material;

class MaterialsFromExcelSeeder extends Seeder
{
    public function run()
    {
        Material::create([
            'code' => 'P-00001',
            'codigo' => 'P-00001',
            'description' => 'PAN FRANCES',
            'full_name' => 'PAN FRANCES',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00002',
            'codigo' => 'P-00002',
            'description' => 'PAN YEMA',
            'full_name' => 'PAN YEMA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00003',
            'codigo' => 'P-00003',
            'description' => 'PAN CARACOL',
            'full_name' => 'PAN CARACOL',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00004',
            'codigo' => 'P-00004',
            'description' => 'PAN COLISA',
            'full_name' => 'PAN COLISA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00005',
            'codigo' => 'P-00005',
            'description' => 'PAN INTEGRAL',
            'full_name' => 'PAN INTEGRAL',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00006',
            'codigo' => 'P-00006',
            'description' => 'PAN BAGUETINO',
            'full_name' => 'PAN BAGUETINO',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00007',
            'codigo' => 'P-00007',
            'description' => 'PAN ARABE',
            'full_name' => 'PAN ARABE',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00008',
            'codigo' => 'P-00008',
            'description' => 'PAN PETEPAN',
            'full_name' => 'PAN PETEPAN',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00009',
            'codigo' => 'P-00009',
            'description' => 'PAN HAMBIURGUESA CHICA',
            'full_name' => 'PAN HAMBIURGUESA CHICA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00010',
            'codigo' => 'P-00010',
            'description' => 'PAN HAMBURGUESA GRANDE',
            'full_name' => 'PAN HAMBURGUESA GRANDE',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.5,
            'list_price' => 0.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00011',
            'codigo' => 'P-00011',
            'description' => 'PAN CAMOTE',
            'full_name' => 'PAN CAMOTE',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00012',
            'codigo' => 'P-00012',
            'description' => 'PAN DE JAMONADA',
            'full_name' => 'PAN DE JAMONADA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.4,
            'list_price' => 0.4,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00013',
            'codigo' => 'P-00013',
            'description' => 'PAN DE MOLDE GRANDE',
            'full_name' => 'PAN DE MOLDE GRANDE',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 12,
            'list_price' => 12,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00014',
            'codigo' => 'P-00014',
            'description' => 'PAN DE MOLDE CHICO',
            'full_name' => 'PAN DE MOLDE CHICO',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 9,
            'list_price' => 9,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00015',
            'codigo' => 'P-00015',
            'description' => 'PAN CAMPESINO',
            'full_name' => 'PAN CAMPESINO',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 3.5,
            'list_price' => 3.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00016',
            'codigo' => 'P-00016',
            'description' => 'PAN TORTUGA',
            'full_name' => 'PAN TORTUGA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 4,
            'list_price' => 4,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00017',
            'codigo' => 'P-00017',
            'description' => 'CARAMANDUCA ',
            'full_name' => 'CARAMANDUCA ',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00018',
            'codigo' => 'P-00018',
            'description' => 'CACHITO MANJAR',
            'full_name' => 'CACHITO MANJAR',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 2.5,
            'list_price' => 2.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00019',
            'codigo' => 'P-00019',
            'description' => 'CACHITO MANTEQUILLA',
            'full_name' => 'CACHITO MANTEQUILLA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 2.5,
            'list_price' => 2.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00020',
            'codigo' => 'P-00020',
            'description' => 'ENCIMADO',
            'full_name' => 'ENCIMADO',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 1,
            'list_price' => 1,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00021',
            'codigo' => 'P-00021',
            'description' => 'PAN DE LEHE',
            'full_name' => 'PAN DE LEHE',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.4,
            'list_price' => 0.4,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00022',
            'codigo' => 'P-00022',
            'description' => 'CIABATTA',
            'full_name' => 'CIABATTA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 0.3,
            'list_price' => 0.3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00023',
            'codigo' => 'P-00023',
            'description' => 'BIZCOCHO BOLSA',
            'full_name' => 'BIZCOCHO BOLSA',
            'brand_id' => 1,
            'unit_measure_id' => 3,
            'category_id' => 1,
            'subcategory_id' => 1,
            'perecible' => 'n',
            'unit_price' => 6,
            'list_price' => 6,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00024',
            'codigo' => 'P-00024',
            'description' => 'MILOJAS',
            'full_name' => 'MILOJAS',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 4,
            'list_price' => 4,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00025',
            'codigo' => 'P-00025',
            'description' => 'CONO',
            'full_name' => 'CONO',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 4,
            'list_price' => 4,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00026',
            'codigo' => 'P-00026',
            'description' => 'PAÑUELO',
            'full_name' => 'PAÑUELO',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 3,
            'list_price' => 3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00027',
            'codigo' => 'P-00027',
            'description' => 'PASTEL DE MANZANA',
            'full_name' => 'PASTEL DE MANZANA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 3.5,
            'list_price' => 3.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00028',
            'codigo' => 'P-00028',
            'description' => 'OREJA',
            'full_name' => 'OREJA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 1.5,
            'list_price' => 1.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00029',
            'codigo' => 'P-00029',
            'description' => 'EMPANADA POLLO',
            'full_name' => 'EMPANADA POLLO',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 3.5,
            'list_price' => 3.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00030',
            'codigo' => 'P-00030',
            'description' => 'EMPANADA CARNE',
            'full_name' => 'EMPANADA CARNE',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 3.5,
            'list_price' => 3.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00031',
            'codigo' => 'P-00031',
            'description' => 'EMPANADA MIXTA',
            'full_name' => 'EMPANADA MIXTA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 3.5,
            'list_price' => 3.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00032',
            'codigo' => 'P-00032',
            'description' => 'QUEQUE PIÑA',
            'full_name' => 'QUEQUE PIÑA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 2,
            'list_price' => 2,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00033',
            'codigo' => 'P-00033',
            'description' => 'ENROLLADO CHORIZO',
            'full_name' => 'ENROLLADO CHORIZO',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 2,
            'list_price' => 2,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00034',
            'codigo' => 'P-00034',
            'description' => 'COCADA',
            'full_name' => 'COCADA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 1.5,
            'list_price' => 1.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00035',
            'codigo' => 'P-00035',
            'description' => 'ALFAJOR',
            'full_name' => 'ALFAJOR',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 3,
            'list_price' => 3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00036',
            'codigo' => 'P-00036',
            'description' => 'EMPANADA DULCE GRANDE',
            'full_name' => 'EMPANADA DULCE GRANDE',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 1.5,
            'list_price' => 1.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00037',
            'codigo' => 'P-00037',
            'description' => 'QUEQUE PIÑA GRANDE',
            'full_name' => 'QUEQUE PIÑA GRANDE',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 25,
            'list_price' => 25,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00038',
            'codigo' => 'P-00038',
            'description' => 'QUEQUE PIÑA PEQUEÑO',
            'full_name' => 'QUEQUE PIÑA PEQUEÑO',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 15,
            'list_price' => 15,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00039',
            'codigo' => 'P-00039',
            'description' => 'QUEQUE VAINILLA',
            'full_name' => 'QUEQUE VAINILLA',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 2,
            'perecible' => 'n',
            'unit_price' => 20,
            'list_price' => 20,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00040',
            'codigo' => 'P-00040',
            'description' => 'BUDIN',
            'full_name' => 'BUDIN',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 28,
            'list_price' => 28,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00041',
            'codigo' => 'P-00041',
            'description' => 'SELVA NEGRA',
            'full_name' => 'SELVA NEGRA',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 63,
            'list_price' => 63,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00042',
            'codigo' => 'P-00042',
            'description' => 'SELVA NEGRA MINI',
            'full_name' => 'SELVA NEGRA MINI',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 35,
            'list_price' => 35,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00043',
            'codigo' => 'P-00043',
            'description' => 'TORTA HELADA GRANDE',
            'full_name' => 'TORTA HELADA GRANDE',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 45,
            'list_price' => 45,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00044',
            'codigo' => 'P-00044',
            'description' => 'TORTA HELADA MEDIANA',
            'full_name' => 'TORTA HELADA MEDIANA',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 35,
            'list_price' => 35,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00045',
            'codigo' => 'P-00045',
            'description' => 'TORTA HELADA MINI',
            'full_name' => 'TORTA HELADA MINI',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 25,
            'list_price' => 25,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00046',
            'codigo' => 'P-00046',
            'description' => 'TORTA VAINILLA GRANDE',
            'full_name' => 'TORTA VAINILLA GRANDE',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 53,
            'list_price' => 53,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00047',
            'codigo' => 'P-00047',
            'description' => 'TORTA VAINILLA MEDIANA',
            'full_name' => 'TORTA VAINILLA MEDIANA',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 48,
            'list_price' => 48,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00048',
            'codigo' => 'P-00048',
            'description' => 'TORTA VAINILLA CHICA',
            'full_name' => 'TORTA VAINILLA CHICA',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 35,
            'list_price' => 35,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00049',
            'codigo' => 'P-00049',
            'description' => 'CREMA VOLTEADA',
            'full_name' => 'CREMA VOLTEADA',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 45,
            'list_price' => 45,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00050',
            'codigo' => 'P-00050',
            'description' => 'TRES LECHES GRANDE',
            'full_name' => 'TRES LECHES GRANDE',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 70,
            'list_price' => 70,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00051',
            'codigo' => 'P-00051',
            'description' => 'TRES LECHES MEDIANO',
            'full_name' => 'TRES LECHES MEDIANO',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 50,
            'list_price' => 50,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00052',
            'codigo' => 'P-00052',
            'description' => 'TRES LECHES CHICO',
            'full_name' => 'TRES LECHES CHICO',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 45,
            'list_price' => 45,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00053',
            'codigo' => 'P-00053',
            'description' => 'TORTA SUBLIME GRANDE',
            'full_name' => 'TORTA SUBLIME GRANDE',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 65,
            'list_price' => 65,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00054',
            'codigo' => 'P-00054',
            'description' => 'TORTA SUBLIME CHICO',
            'full_name' => 'TORTA SUBLIME CHICO',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 40,
            'list_price' => 40,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00055',
            'codigo' => 'P-00055',
            'description' => 'TORTA CAFÉ GRANDE',
            'full_name' => 'TORTA CAFÉ GRANDE',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 63,
            'list_price' => 63,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00056',
            'codigo' => 'P-00056',
            'description' => 'TORTA CAFÉ MINI',
            'full_name' => 'TORTA CAFÉ MINI',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 35,
            'list_price' => 35,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00057',
            'codigo' => 'P-00057',
            'description' => 'OREO GRANDE',
            'full_name' => 'OREO GRANDE',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 63,
            'list_price' => 63,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00058',
            'codigo' => 'P-00058',
            'description' => 'OREO MINI',
            'full_name' => 'OREO MINI',
            'brand_id' => 1,
            'unit_measure_id' => 2,
            'category_id' => 2,
            'subcategory_id' => 3,
            'perecible' => 'n',
            'unit_price' => 35,
            'list_price' => 35,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00059',
            'codigo' => 'P-00059',
            'description' => 'MUS VASITO',
            'full_name' => 'MUS VASITO',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 4,
            'perecible' => 'n',
            'unit_price' => 3,
            'list_price' => 3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00060',
            'codigo' => 'P-00060',
            'description' => 'MUS TAPER',
            'full_name' => 'MUS TAPER',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 4,
            'perecible' => 'n',
            'unit_price' => 4,
            'list_price' => 4,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00061',
            'codigo' => 'P-00061',
            'description' => 'MUS IMPERIAL',
            'full_name' => 'MUS IMPERIAL',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 4,
            'perecible' => 'n',
            'unit_price' => 4,
            'list_price' => 4,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00062',
            'codigo' => 'P-00062',
            'description' => 'LECHE ASADA',
            'full_name' => 'LECHE ASADA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 4,
            'perecible' => 'n',
            'unit_price' => 3.5,
            'list_price' => 3.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00063',
            'codigo' => 'P-00063',
            'description' => 'BUDIN',
            'full_name' => 'BUDIN',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 4,
            'perecible' => 'n',
            'unit_price' => 1.5,
            'list_price' => 1.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00064',
            'codigo' => 'P-00064',
            'description' => 'CHOCOFLAN',
            'full_name' => 'CHOCOFLAN',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 4,
            'perecible' => 'n',
            'unit_price' => 6,
            'list_price' => 6,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00065',
            'codigo' => 'P-00065',
            'description' => 'TORTA HELADA',
            'full_name' => 'TORTA HELADA',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 4,
            'perecible' => 'n',
            'unit_price' => 4,
            'list_price' => 4,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00066',
            'codigo' => 'P-00066',
            'description' => 'TARTALETA DURAZNO',
            'full_name' => 'TARTALETA DURAZNO',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 4,
            'perecible' => 'n',
            'unit_price' => 4.5,
            'list_price' => 4.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00067',
            'codigo' => 'P-00067',
            'description' => 'PASTEL CHOCLO',
            'full_name' => 'PASTEL CHOCLO',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 4,
            'perecible' => 'n',
            'unit_price' => 3,
            'list_price' => 3,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00068',
            'codigo' => 'P-00068',
            'description' => 'TORTA CHOCOLATE',
            'full_name' => 'TORTA CHOCOLATE',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 4,
            'perecible' => 'n',
            'unit_price' => 6,
            'list_price' => 6,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00069',
            'codigo' => 'P-00069',
            'description' => 'QUEQUE VAINILLA ',
            'full_name' => 'QUEQUE VAINILLA ',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 4,
            'perecible' => 'n',
            'unit_price' => 1.5,
            'list_price' => 1.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00070',
            'codigo' => 'P-00070',
            'description' => 'NIDO DE AMOR x3',
            'full_name' => 'NIDO DE AMOR x3',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 1,
            'list_price' => 1,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00071',
            'codigo' => 'P-00071',
            'description' => 'NIDO DE AMOR x25',
            'full_name' => 'NIDO DE AMOR x25',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 10,
            'list_price' => 10,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00072',
            'codigo' => 'P-00072',
            'description' => 'NIDO DE AMOR x50',
            'full_name' => 'NIDO DE AMOR x50',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 20,
            'list_price' => 20,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00073',
            'codigo' => 'P-00073',
            'description' => 'NIDO DE AMOR x100',
            'full_name' => 'NIDO DE AMOR x100',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 40,
            'list_price' => 40,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00074',
            'codigo' => 'P-00074',
            'description' => 'ALFAJORCITO x3',
            'full_name' => 'ALFAJORCITO x3',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 1,
            'list_price' => 1,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00075',
            'codigo' => 'P-00075',
            'description' => 'ALFAJORCITO x25',
            'full_name' => 'ALFAJORCITO x25',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 10,
            'list_price' => 10,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00076',
            'codigo' => 'P-00076',
            'description' => 'ALFAJORCITO x50',
            'full_name' => 'ALFAJORCITO x50',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 20,
            'list_price' => 20,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00077',
            'codigo' => 'P-00077',
            'description' => 'ALFAJORCITO x100',
            'full_name' => 'ALFAJORCITO x100',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 40,
            'list_price' => 40,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00078',
            'codigo' => 'P-00078',
            'description' => 'EMPANADA DULCE BOCADITO x3',
            'full_name' => 'EMPANADA DULCE BOCADITO x3',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 1,
            'list_price' => 1,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00079',
            'codigo' => 'P-00079',
            'description' => 'EMPANADA DULCE BOCADITO x25',
            'full_name' => 'EMPANADA DULCE BOCADITO x25',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 10,
            'list_price' => 10,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00080',
            'codigo' => 'P-00080',
            'description' => 'EMPANADA DULCE BOCADITO x50',
            'full_name' => 'EMPANADA DULCE BOCADITO x50',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 20,
            'list_price' => 20,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00081',
            'codigo' => 'P-00081',
            'description' => 'EMPANADA DULCE BOCADITO x100',
            'full_name' => 'EMPANADA DULCE BOCADITO x100',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 40,
            'list_price' => 40,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00082',
            'codigo' => 'P-00082',
            'description' => 'OREJITAS x25',
            'full_name' => 'OREJITAS x25',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 12.5,
            'list_price' => 12.5,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00083',
            'codigo' => 'P-00083',
            'description' => 'OREJITAS x50',
            'full_name' => 'OREJITAS x50',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 25,
            'list_price' => 25,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00084',
            'codigo' => 'P-00084',
            'description' => 'OREJITAS x100',
            'full_name' => 'OREJITAS x100',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 50,
            'list_price' => 50,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00085',
            'codigo' => 'P-00085',
            'description' => 'EMPANADITAS DE POLLO x25',
            'full_name' => 'EMPANADITAS DE POLLO x25',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 15,
            'list_price' => 15,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00086',
            'codigo' => 'P-00086',
            'description' => 'EMPANADITAS DE POLLO x50',
            'full_name' => 'EMPANADITAS DE POLLO x50',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 30,
            'list_price' => 30,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00087',
            'codigo' => 'P-00087',
            'description' => 'EMPANADITAS DE POLLO x100',
            'full_name' => 'EMPANADITAS DE POLLO x100',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 60,
            'list_price' => 60,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00088',
            'codigo' => 'P-00088',
            'description' => 'EMPANADITAS DE CARNE x25',
            'full_name' => 'EMPANADITAS DE CARNE x25',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 15,
            'list_price' => 15,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00089',
            'codigo' => 'P-00089',
            'description' => 'EMPANADITAS DE CARNE x50',
            'full_name' => 'EMPANADITAS DE CARNE x50',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 30,
            'list_price' => 30,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00090',
            'codigo' => 'P-00090',
            'description' => 'EMPANADITAS DE CARNE x100',
            'full_name' => 'EMPANADITAS DE CARNE x100',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 60,
            'list_price' => 60,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00091',
            'codigo' => 'P-00091',
            'description' => 'ENROLLADITO DE HOT DOG x25',
            'full_name' => 'ENROLLADITO DE HOT DOG x25',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 15,
            'list_price' => 15,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00092',
            'codigo' => 'P-00092',
            'description' => 'ENROLLADITO DE HOT DOG x50',
            'full_name' => 'ENROLLADITO DE HOT DOG x50',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 30,
            'list_price' => 30,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

        Material::create([
            'code' => 'P-00093',
            'codigo' => 'P-00093',
            'description' => 'ENROLLADITO DE HOT DOG x100',
            'full_name' => 'ENROLLADITO DE HOT DOG x100',
            'brand_id' => 1,
            'unit_measure_id' => 1,
            'category_id' => 2,
            'subcategory_id' => 5,
            'perecible' => 'n',
            'unit_price' => 60,
            'list_price' => 60,
            'enable_status' => 1,
            'inventory' => 1,
            'stock_current' => 0,
            'stock_reserved' => 0,
        ]);

    }
}

